import 'package:hdi_test/models/member_model.dart';
import 'package:hdi_test/models/transaction_model.dart';
import 'package:hdi_test/utils/enums/transaction_category.dart';
import 'package:hdi_test/utils/enums/transaction_status.dart';

class MockData {
  static final MemberModel member = MemberModel(
    id: 'MB001',
    name: 'Galih Baskoro',
    city: 'Jakarta',
    joinDate: DateTime(2022, 3, 15),
    membershipStatus: 'Gold',
  );

  static final List<TransactionModel> transactions = [
    TransactionModel(
      id: 'TRX001',
      date: DateTime(2026, 5, 20),
      category: TransactionCategory.electronics,
      amount: 1250000,
      status: TransactionStatus.paid,
      description: 'Wireless Headphones',
    ),
    TransactionModel(
      id: 'TRX002',
      date: DateTime(2026, 5, 15),
      category: TransactionCategory.food,
      amount: 185000,
      status: TransactionStatus.paid,
      description: 'Grocery Shopping',
    ),
    TransactionModel(
      id: 'TRX003',
      date: DateTime(2026, 5, 10),
      category: TransactionCategory.clothing,
      amount: 450000,
      status: TransactionStatus.pending,
      description: 'Summer Collection Shirt',
    ),
    TransactionModel(
      id: 'TRX004',
      date: DateTime(2026, 5, 5),
      category: TransactionCategory.health,
      amount: 320000,
      status: TransactionStatus.paid,
      description: 'Vitamins & Supplements',
    ),
    TransactionModel(
      id: 'TRX005',
      date: DateTime(2026, 5, 1),
      category: TransactionCategory.entertainment,
      amount: 99000,
      status: TransactionStatus.paid,
      description: 'Streaming Subscription',
    ),
    TransactionModel(
      id: 'TRX006',
      date: DateTime(2026, 4, 28),
      category: TransactionCategory.travel,
      amount: 2100000,
      status: TransactionStatus.paid,
      description: 'Train Ticket - Jakarta to Surabaya',
    ),
    TransactionModel(
      id: 'TRX007',
      date: DateTime(2026, 4, 20),
      category: TransactionCategory.food,
      amount: 275000,
      status: TransactionStatus.failed,
      description: 'Restaurant Dinner',
    ),
    TransactionModel(
      id: 'TRX008',
      date: DateTime(2026, 4, 15),
      category: TransactionCategory.electronics,
      amount: 850000,
      status: TransactionStatus.refunded,
      description: 'Mechanical Keyboard',
    ),
    TransactionModel(
      id: 'TRX009',
      date: DateTime(2026, 4, 10),
      category: TransactionCategory.health,
      amount: 150000,
      status: TransactionStatus.paid,
      description: 'Pharmacy Purchase',
    ),
    TransactionModel(
      id: 'TRX010',
      date: DateTime(2026, 4, 5),
      category: TransactionCategory.clothing,
      amount: 780000,
      status: TransactionStatus.paid,
      description: 'Running Shoes',
    ),
    TransactionModel(
      id: 'TRX011',
      date: DateTime(2026, 3, 25),
      category: TransactionCategory.entertainment,
      amount: 250000,
      status: TransactionStatus.paid,
      description: 'Cinema Tickets x4',
    ),
    TransactionModel(
      id: 'TRX012',
      date: DateTime(2026, 3, 18),
      category: TransactionCategory.travel,
      amount: 1500000,
      status: TransactionStatus.pending,
      description: 'Hotel Booking',
    ),
    TransactionModel(
      id: 'TRX013',
      date: DateTime(2026, 3, 10),
      category: TransactionCategory.food,
      amount: 95000,
      status: TransactionStatus.paid,
      description: 'Coffee & Snacks',
    ),
    TransactionModel(
      id: 'TRX014',
      date: DateTime(2026, 2, 22),
      category: TransactionCategory.electronics,
      amount: 3500000,
      status: TransactionStatus.paid,
      description: 'Tablet Device',
    ),
    TransactionModel(
      id: 'TRX015',
      date: DateTime(2026, 2, 14),
      category: TransactionCategory.other,
      amount: 125000,
      status: TransactionStatus.paid,
      description: 'Gift Wrapping Service',
    ),
    TransactionModel(
      id: 'TRX016',
      date: DateTime(2026, 1, 30),
      category: TransactionCategory.health,
      amount: 500000,
      status: TransactionStatus.paid,
      description: 'Dental Checkup',
    ),
    TransactionModel(
      id: 'TRX017',
      date: DateTime(2026, 1, 20),
      category: TransactionCategory.clothing,
      amount: 620000,
      status: TransactionStatus.paid,
      description: 'Winter Jacket',
    ),
    TransactionModel(
      id: 'TRX018',
      date: DateTime(2025, 12, 31),
      category: TransactionCategory.entertainment,
      amount: 350000,
      status: TransactionStatus.paid,
      description: 'New Year Concert Ticket',
    ),
    TransactionModel(
      id: 'TRX019',
      date: DateTime(2026, 06, 2),
      category: TransactionCategory.other,
      amount: 450000,
      status: TransactionStatus.refunded,
      description: 'Delta Premium Service',
    ),
    TransactionModel(
      id: 'TRX020',
      date: DateTime(2026, 06, 3),
      category: TransactionCategory.travel,
      amount: 1350000,
      status: TransactionStatus.paid,
      description: 'Ticket To Orsterra - Planetarium',
    ),
  ];
}
